name: Main Workflow Dispatcher

on:
  push:
    branches:
      - "**"   # Runs on all branches except master (handled separately)
  pull_request:
    branches:
      - "**"

jobs:
  test:
    #uses: ./.github/workflows/partiallyworkflows/test-workflow.yml  # Calls test workflow
    uses: ./.github/actions/includeworkflows/test-workflow  # Calls test workflow
  
  build:
    #uses: ./.github/workflows/partiallyworkflows/build-workflow.yml  # Calls build workflow
    uses: ./.github/actions/includeworkflows/build-workflow  # Calls build workflow

  #deploy:
   # if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'  # Only deploy on master/main
   # uses: ./.github/workflows/partiallyworkflows/deploy-workflow-example.yml